# Copyright Contributors to the Open Cluster Management project
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: mce
spec:
  displayName: Red Hat MultiCluster Engine
  proxy:
    - type: Service
      alias: console
      service:
        name: console-mce-console
        namespace: {{ .Values.global.namespace }}
        port: 3000
      authorize: true
  service:
    basePath: /plugin/
    name: console-mce-console
    namespace: {{ .Values.global.namespace }}
    port: 3000
